import networkx as nx

g = nx.Graph()
g.add_edge("Starting_Skill", "First_Powerup")
g.add_edge("First_Powerup", "Defense_Range_Starter")
g.add_edge("First_Powerup", "Magic_Starter")
g.add_edge("First_Powerup", "Attack_Starter")
g.add_edge("Defense_Range_Starter", "Bow_Arrow")
g.add_edge("Defense_Range_Starter", "Iron_Shield")
g.add_edge("Bow_Arrow", "Crossbow")
g.add_edge("Bow_Arrow", "Elemental_Arrows")
g.add_edge("Crossbow", "Elemental_Arrows")
g.add_edge("Magic_Starter", "Magic_Wand")
g.add_edge("Magic_Starter", "Learn_Spells")
g.add_edge("Magic_Wand", "Ice_Cast")
g.add_edge("Magic_Wand", "Fire_Cast")
g.add_edge("Learn_Spells", "Ice_Cast")
g.add_edge("Learn_Spells", "Fire_Cast")
g.add_edge("Learn_Spells", "Magic_Shield")
g.add_edge("Iron_Shield", "Magic_Shield")
g.add_edge("Ice_Cast", "Elemental_Arrows")
g.add_edge("Fire_Cast", "Elemental_Arrows")
g.add_edge("Fire_Cast", "Flaming_Sword")
g.add_edge("Attack_Starter", "Iron_Shield")
g.add_edge("Attack_Starter", "Iron_Sword")
g.add_edge("Attack_Starter", "Light_Armor")
g.add_edge("Iron_Shield", "Light_Armor")
g.add_edge("Light_Armor", "Assassin_Dagger")
g.add_edge("Attack_Starter", "Assassin_Dagger")
g.add_edge("Assassin_Dagger", "Dual_Weild")
g.add_edge("Iron_Sword", "Broadsword")
g.add_edge("Iron_Sword", "Greatsword")
g.add_edge("Iron_Sword", "Dual_Weild")
g.add_edge("Broadsword", "Greatsword")
g.add_edge("Broadsword", "Flaming_Sword")

if __name__ == "__main__":
    N = nx.bfs_edges(g, 'Starting_Skill')
    bfs = list(N)
    print(bfs)